apiVersion : apps/v1
kind: Deployment
metadata:
  name: shelkecicdusingdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelkecicdusingdocker
  template:
    metadata:
      labels:
        app: shelkecicdusingdocker 
    spec:
      containers:
        - name: shelkecicdusingdocker 
          image: dhananjayshelke/shelkepatil:latest 
          ports:
          - containerPort: 8080  
          
---
          
apiVersion: v1
kind: Service
metadata:
    name: shelkecicdusingdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: shelkecicdusingdocker
          
